import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./ components/NavBar";
import { SessionProvider } from "next-auth/react";
import { NotificationContextProvider } from "./ components/NotificationContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Blogapp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased m-4`}
    >
      <body className="min-h-full flex flex-col">
        <SessionProvider>
          <NavBar />
          <NotificationContextProvider>{children}</NotificationContextProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
